# ä¸»é è¨­å®š
languageCode = "zh-tw"
languageName = "ä¸­æ–‡ğŸ‡¹ğŸ‡¼"
weight = 1
title = "ZSL"

[params]
  displayName = "ä¸­æ–‡ğŸ‡¹ğŸ‡¼"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006å¹´1æœˆ2æ—¥"
  #logo = "img/global/zsl.webp"
  description = "ZSL çš„ç­†è¨˜ç©ºé–“"

[author]
  name = "ZSL"
  image = "img/zsl.webp"
  #headline = "The Empire of Shinonome Umi"
  bio = "æ­£äº‹ä¸åšã€‚"
  links = [
    { email = "mailto:leo01412123@gmail.com" },
    { youtube = "https://www.youtube.com/@umi_shinonome/videos" },
    { instagram = "https://www.instagram.com/umi_portrait/" },
    { tiktok = "https://www.tiktok.com/@shinonome_umi" },
    { egg = "https://shinonomeumi-fc.com/" },
    { dribbble = "https://ppe.jp/" },
    { x-twitter = "https://x.com/sinonome_umi/" },
    { github = "https://github.com/ZhenShuo2021/" },
  ]