# ä¸»é è¨­å®š
languageCode = "en"
languageName = "ENğŸ‡ºğŸ‡¸"
weight = 2
title = "ZSL"

[params]
  displayName = "ENğŸ‡ºğŸ‡¸"
  isoCode = "en-us"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/blowfish_logo_transparent.png"
  #description = "ZSL's Space."

[author]
  name = "ZSL"
  image = "img/zsl.webp"
  #headline = "The Empire of Shinonome Umi"
  bio = "Sloth is good."
  links = [
    { email = "mailto:leo01412123@gmail.com" },
    { youtube = "https://www.youtube.com/@umi_shinonome/videos" },
    { instagram = "https://www.instagram.com/umi_portrait/" },
    { tiktok = "https://www.tiktok.com/@shinonome_umi" },
    { egg = "https://shinonomeumi-fc.com/" },
    { dribbble = "https://ppe.jp/" },
    { x-twitter = "https://x.com/sinonome_umi/" },
    { github = "https://github.com/ZhenShuo2021/" },
  ]